#ifndef ENUMS_PARSER_H_
#define ENUMS_PARSER_H_

enum TokenType
{
	INVALID = -1,
	ACCESS_MODIFIER = 0,
	LABEL = 1,
	SECTION = 2,
	DIRECTIVE = 3,
	INSTRUCTION = 4,
	SYMBOL = 5,
	END_OF_FILE = 6,
	OPERAND_IMMEDIATELY_DECIMAL = 7,
	OPERAND_IMMEDIATELY_HEX = 8,
	OPERAND_REGISTER_DIRECT = 9,
	OPERAND_REGISTER_INDIRECT = 10,
	OPERAND_MEMORY_DIRECT_DECIMAL = 11,
	OPERAND_MEMORY_DIRECT_HEX = 12,
	OPERAND_IMMEDIATELY_SYMBOL = 13,
	OPERAND_PC_RELATIVE_SYMBOL = 14
};

#endif