#ifndef ENUMS_PARSER_H_
#define ENUMS_PARSER_H_

#define ASM_UNDEFINED -1

enum TokenType
{
	INVALID = -1,
	ACCESS_MODIFIER = 0,
	LABEL = 1,
	SECTION = 2,
	DIRECTIVE = 3,
	INSTRUCTION = 4,
	SYMBOL = 5,
	END_OF_FILE = 6,
	OPERAND_IMMEDIATELY_DECIMAL = 7,
	OPERAND_IMMEDIATELY_HEX = 8,
	OPERAND_REGISTER_DIRECT = 9,
	OPERAND_REGISTER_INDIRECT = 10,
	OPERAND_MEMORY_DIRECT_DECIMAL = 11,
	OPERAND_MEMORY_DIRECT_HEX = 12,
	OPERAND_IMMEDIATELY_SYMBOL = 13,
	OPERAND_PC_RELATIVE_SYMBOL = 14,
	FLAGS = 15,
	ARITHMETIC_OPERATOR = 16,
	ARITHMETIC_EXPRESSION = 17
};

enum OperandSize
{
	BYTE = 0,
	WORD = 1
};

enum AddressingType
{
	IMMEDIATELY = 0,
	REGISTER_DIRECT,
	REGISTER_INDIRECT_NO_OFFSET,
	REGISTER_INDIRECT_8_BIT_OFFSET,
	REGISTER_INDIRECT_16_BIT_OFFSET,
	MEMORY_DIRECT
};

enum Operand
{
	FIRST_OPERAND,
	SECOND_OPERAND
};

enum ByteSelector
{
	NOT_APPLICABLE = -1,
	LOWER = 0,
	HIGHER = 1,
};

enum InterruptType
{
	RESET = 0,
	INT_INVALID_INSTRUCTION = 1,
	TIMER = 2,
	KEYBOARD = 3
};

#endif